//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demeter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Childcare
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string BusinessType { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string NameOfBusiness { get; set; }
        public string PhoneNumber { get; set; }
        public string Suburb { get; set; }
    }
}
