//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demeter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingTK
    {
        public int Id { get; set; }
        public string Suburb { get; set; }
        public string ratioNormalised { get; set; }
        public string wsNormalised { get; set; }
        public string ccNormalised { get; set; }
        public string lgNormalised { get; set; }
        public string schoolNormalised { get; set; }
    }
}
