//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demeter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int Id { get; set; }
        public string EducationSector { get; set; }
        public string SchoolName { get; set; }
        public string AddressLine { get; set; }
        public string AddressType { get; set; }
        public string AddressTown { get; set; }
        public string AddressState { get; set; }
        public string AddressPostcode { get; set; }
        public string FullPhoneNo { get; set; }
        public string LGAID { get; set; }
        public string LGAName { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
    }
}
