//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demeter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int Id { get; set; }
        public string stopName { get; set; }
        public string stopLat { get; set; }
        public string stopLon { get; set; }
        public string routeType { get; set; }
        public string routeShortName { get; set; }
        public string Suburb { get; set; }
    }
}
